### ISSUE TITLE
Craft 4: can't remove custom styles

### ISSUE THREAD

**Issue by MetaDevelopment** [carlcs/craft-redactorinlinestyles#31]
Thanks for the plugin, I love it and use it on all my projects! 

Creating a first project on Craft 4 now and running into the following issue: 

Adding a custom style works fine, a span with the class is appended as set up in the json-file (toggle a class to color the text red, see below). 

When trying to remove the style by clicking the clear styles button, the custom style seems to be removed (the selected text is no longer red), however: 

- when I switch to HTML-view, I can still see the span with custom class and when I then switch back to 'normal' view the text is red again 
- when I save the page the text turns red again, so the removal does not get saved (even if I don't switch to HTML-view before saving) 

I tested this in a clean setup: 

- Craft CMS 4(.03) 
- Plugins Redactor (3.0.0) and Redactor Custom Styles (4.0.0) 
- Only one Redactor field on a single section 

Settings: 

```
{
    "buttons": [
      "html",
      "formatting",
      "unorderedlist",
      "orderedlist",
      "link"
    ],
  "plugins": ["customstyles"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "customStyles": {
    "Style": {
      "dropdown": {
        "Red": {
          "args": {
            "tag": "span",
            "class": "red",
            "type": "toggle"
          }
        }
      }
    },
    "clearStyles": {
      "api": "module.inline.clearformat"
    }
  }
}
```

Do I need to change something in my setup for Craft CMS 4 or Redactor 3?

**Comment by carlcs** [comment]
Thanks for reporting the issue! There seems to be a bug with Redactor "module.inline.clearformat" API where it’s not syncing the updated content to the textarea input. This will probably get fixed in a future Redactor update. https://imperavi.com/redactor/log/

Because a “Clear Styles” button is a critical feature of the plugin, I have just added a fix where the plugin triggers a manual sync on every button press.
