### ISSUE TITLE
Plugin not compatible with codemonauts/craft-redactor-nofollow

### ISSUE THREAD

**Issue by WHITE-developer** [carlcs/craft-redactorinlinestyles#35]
When installing both your plugin and codemonauts/craft-redactor-nofollow, we get an error in craft:

![image](https://user-images.githubusercontent.com/22771556/195801671-915af9c6-5886-45f1-99e2-652caa66057c.png)

This happens when we want to use "customstyles" plugin in a redactor setting.

Craft CMS: 3.7.37
codemonauts/craft-redactor-nofollow: 1.0.1
carlcs/craft-redactorcustomstyles: 3.0.4

**Comment by carlcs** [comment]
The issue seems to be caused by the “nofollow” plugin. They are calling `craft\redactor\Field::registerRedactorPlugin()` which I think they shouldn’t. It prevents other redactor plugins from registering.

https://github.com/codemonauts/craft-redactor-nofollow/blob/1.0.1/src/Nofollow.php#L26

Can you please open an issue over at the Codemonauts repo and link this issue for reference. I’ll close here for now, but please let me know if I can assist with anything else to get this fixed for you. Thanks
